# This file is generated by Nx.
#
# Build the docker image with `npx nx docker-build test-nx-node`.
# Tip: Modify "docker-build" options in project.json to change docker build args.
#
# Run the container with `docker run -p 3000:3000 -t test-nx-node`.
FROM docker.io/node:lts-alpine

ENV HOST=0.0.0.0
ENV PORT=3000

WORKDIR /app

RUN addgroup --system test-nx-node && \
          adduser --system -G test-nx-node test-nx-node

COPY dist/test-nx-node test-nx-node/
RUN chown -R test-nx-node:test-nx-node .

# You can remove this install step if you build with `--bundle` option.
# The bundled output will include external dependencies.
RUN npm --prefix test-nx-node --omit=dev -f install

CMD [ "node", "test-nx-node" ]
